---
- name: debian | Installing pre-reqs
  apt:
    name: "ca-certificiates"
    state: "present"

- name: debian | Installing dumb-init
  apt:
    deb: "{{ dumb_init_debian_package }}"
    state: "present"
